version: '3.1'
services:
  api:
    build: skattela/epc_qr_code_app
    container_name: epc_qr_code_app
    ports:
      - 80:80
    env_file:
      - .env

networks:
  default:
    external:
      name: api
