openapi: "3.0.0"

info:
  title: EPC-QR-Code
  version: "1.0"

servers:
  - url: {{api_url}}
    description: Server

paths:
  /rest/webhook/{jira_ticket}:
    post:
      summary: Trigger webhook
      operationId: main.webhook
      parameters:
        - name: jira_ticket
          in: path
          description: User ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
      security:
        - api_key: []
  /rest/epc_qrcode:
    post:
      summary: Trigger webhook
      operationId: main.post_epc_qrcode
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                iban:
                  type: string
                amount:
                  type: number
                reference:
                  type: string
                additional_text:
                  type: string
              required:
                - name
                - iban
                - amount
                - reference
            example:
              name: "John Doe"
              iban: "DE 12 3456 7890 12"
              amount: 1
              reference: "Donation"
      responses:
        '200':
          description: Logo image in PNG format
          content:
            image/png:
              schema:
                type: string
                format: binary
      security:
        - api_key: []
  /rest/update:
    post:
      summary: Trigger update
      operationId: main.update
      responses:
        '200':
          description: Response
      security:
        - api_key: []

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Auth
      in: query
      x-apikeyInfoFunc: main.apikey_auth