version: 2
jobs:
  build:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Test
          command: |
            virtualenv epc_qr_code_app
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt


      - setup_remote_docker:
          docker_layer_caching: false
      # with credentials stored in the UI
      - run: |
          echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      # build the application image
      - run: docker build -t skattela/epc_qr_code_app_circleci:$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push skattela/epc_qr_code_app_circleci:$CIRCLE_BRANCH